# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mdi.js auto updater
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - id: remote_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: Templarian/MaterialDesign-JS
          releases-only: false

      - id: local_version
        uses: amochkin/action-json@v1
        with:
          mode: read
          property: 'devDependencies.@mdi/js'
          fallback: 1.0.0

      - name: Output variables
        shell: bash
        run: |
          local_version="${{ steps.local_version.outputs.value }}" 
          remote_version="${{ steps.remote_version.outputs.tag }}"
          remote_version="${remote_version#v}" # remove "v" prefix

          echo "local_version=${local_version}" >> $GITHUB_OUTPUT
          echo "remote_version=${remote_version}" >> $GITHUB_OUTPUT

          if [ "$local_version" = "$remote_version" ]; then
            echo "should_update=false"
            echo "should_update=false" >> $GITHUB_OUTPUT
          else
            echo "should_update=true"
            echo "should_update=true" >> $GITHUB_OUTPUT
          fi

  update:
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.should_update == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Update @mdi/js version
        uses: amochkin/action-json@v1
        with:
          mode: write
          property: 'devDependencies.@mdi/js'
          value: ${{ needs.check.outputs.remote_version }}

      - name: Update @garvinallen/vue-material-design-icons version
        uses: amochkin/action-json@v1
        with:
          mode: write
          property: version
          value: ${{ needs.check.outputs.remote_version }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          branch: dev
          message: "chore: bump @mdi/js to ${{ needs.check.outputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
