# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mdi.js auto updater
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  mdijs-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: mdijs version (remote)
        id: mdijs-version-remote
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/Templarian/MaterialDesign-JS

      - name: mdijs version (local)
        id: mdijs-verision-local
        uses: amochkin/action-json@v1
        with:
          mode: read
          property: '@devDependencies.@mdi/js'
          fallback: 1.0.0

      - name: Output variables
        shell: bash
        run: |
          local_version="${{ steps.mdijs-version-local.outputs.value }}"
          remote_version="${{ steps.mdijs-version-remote.outputs.tag }}"
          remote_version="${remote_version#v}" ## remove "v" prefix
          
          # Compare the versions
          if [ "$local_version" == "$remote_version" ]; then
            echo "isUpToDate=true" >> $GITHUB_OUTPUT
            echo "version=${remote_version}" >> $GITHUB_OUTPUT
          else
            echo "isUpToDate=false" >> $GITHUB_OUTPUT
          fi

  update-mdijs-version:
    runs-on: ubuntu-latest
    needs: [mdijs-version]
    if: needs.mdijs-version.outputs.isUpToDate != 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Update @mdi/js version
        uses: amochkin/action-json@v1
        with:
          mode: write
          property: '@devDependencies.@mdi/js'
          value: ${{ needs.mdijs-version.outputs.version }}

      - name: Update @garvinallen/vue-material-design-icons version
        uses: amochkin/action-json@v1
        with:
          mode: write
          property: version
          value: ${{ needs.mdijs-version.outputs.version }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
